stages:
        - containerise
        - verify

variables:
        GIT_STRATEGY: clone
        GIT_SUBMODULE_STRATEGY: recursive
        MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
        DOCKER_TLS_CERTDIR: "/certs"
        DOCKER_DRIVER: overlay2
        CONTAINER: containers
        IMAGE: perfusion_and_tissue_damage 

cache: &global_cache
        paths:
                - ${CONTAINER}/
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull-push

.shared_hidden_key: &docker_definition
        image: docker:19.03.12
        services:
                - docker:19.03.12-dind

build_docker:
        <<: *docker_definition
        cache:
                <<: *global_cache
                policy: push
        stage: containerise
        script:
                - docker build -t ${IMAGE} ./
                - mkdir -p ${CONTAINER}
                - docker save ${IMAGE} > ${CONTAINER}/docker.tar

verify_docker:
        <<: *docker_definition
        cache:
                <<: *global_cache
                policy: pull
        stage: verify
        script:
                - docker load -i ${CONTAINER}/docker.tar
                - mkdir -p ${MOUNT_POINT}/docker
                - docker run -v ${MOUNT_POINT}/docker:/patient ${IMAGE} test -p /patient
