input:
  inlet_BC_type: DBC
  inlet_boundary_file: patient_0/bf_sim/boundary_condition_file.csv
  mesh_file: patient_0/bf_sim/clustered_mesh.xdmf
  permeability_folder: ../brain_meshes/b0000/permeability/
  read_inlet_boundary: true
optimisation:
  FGtarget: 64.48896831397346
  FWtarget: 23.88480307924943
  Fmaxtarget: 80.0
  Fmintarget: 10.0
  init_param_range:
  - - 1
    - 10
  - - 0.0001
    - 0.01
  method: Nelder-Mead
  parameters:
  - gmowm_beta_rat
  - K1gm_ref
  random_init: true
output:
  comp_ave: True
  res_fldr: patient_0/perfusion/
  res_vars: {'press1','vel1','perfusion'}
  integral_vars: {'vel1_surfint','press1_surfave','perfusion_voluave'}
physical:
  K1gm_ref: 0.0021057479999999997
  K2gm_ref: 4.28e-07
  K3gm_ref: 0.0042114959999999995
  beta12gm: 1.8809282424908927e-06
  beta23gm: 6.583248848718124e-06
  gmowm_beta_rat: 2.5648020000000002
  gmowm_perm_rat: 1.0
  p_arterial: 8000
  p_venous: 0.0
simulation:
  fe_degr: 2
  model_type: acv
  vel_order: 1
  cpld_conv_crit: 1.0e-4
  coupled_model: false
